import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { users } from "~/db";

// ============================================================================
// ONTOLOGY GRAPH CONSTANTS (v3 R2)
// ============================================================================

export const OntologyDomain = {
  CUSTOMER: "customer",
  MARKET: "market",
  STRATEGY: "strategy",
  COMPETITION: "competition",
  ECOSYSTEM: "ecosystem",
  RISK: "risk",
  BUSINESS: "business",
  ASSUMPTION: "assumption",
  DECISION: "decision",
} as const;

export const EdgeRelationType = {
  SUPPORTS: "supports",
  CONTRADICTS: "contradicts",
  CAUSES: "causes",
  RELATES_TO: "relates_to",
  DEPENDS_ON: "depends_on",
} as const;

export const DuplicateReviewStatus = {
  PENDING: 0,
  MERGED: 1,
  IGNORED: 2,
} as const;

// ============================================================================
// ONTOLOGY GRAPH TABLES (v3 R2)
// ============================================================================

export const ontologyTypes = sqliteTable("ontology_types", {
  id: text("id").primaryKey(),
  nameKo: text("name_ko").notNull(),
  domain: text("domain").notNull(),
  icon: text("icon"),
  color: text("color").notNull(),
});

export const contextNodes = sqliteTable(
  "context_nodes",
  {
    id: text("id").primaryKey(),
    // cross-BC: no FK reference to discoveries
    discoveryId: text("discovery_id").notNull(),
    label: text("label").notNull(),
    ontologyTypeId: text("ontology_type_id").references(() => ontologyTypes.id),
    sourceEvidenceId: text("source_evidence_id"),
    metadata: text("metadata", { mode: "json" }).$type<Record<string, unknown>>(),
    globalEntityId: text("global_entity_id"),
    confidence: real("confidence").default(1.0),
    autoGenerated: integer("auto_generated").default(0),
    reviewed: integer("reviewed").default(0), // 0=unreviewed, 1=approved, 2=rejected
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (table) => ({
    discoveryIdIdx: index("idx_context_nodes_discovery_id").on(table.discoveryId),
    ontologyTypeIdx: index("idx_context_nodes_ontology_type").on(table.ontologyTypeId),
    sourceEvidenceIdx: index("idx_context_nodes_source_evidence").on(table.sourceEvidenceId),
    globalEntityIdx: index("idx_context_nodes_global_entity").on(table.globalEntityId),
  })
);

export const contextEdges = sqliteTable(
  "context_edges",
  {
    id: text("id").primaryKey(),
    fromNodeId: text("from_node_id")
      .notNull()
      .references(() => contextNodes.id, { onDelete: "cascade" }),
    toNodeId: text("to_node_id")
      .notNull()
      .references(() => contextNodes.id, { onDelete: "cascade" }),
    relationType: text("relation_type").notNull(),
    strength: integer("strength").default(100), // 0~100 (stored as int, display as 0~1)
    sourceEvidenceId: text("source_evidence_id"),
    confidence: real("confidence").default(1.0),
    autoGenerated: integer("auto_generated").default(0),
    reviewed: integer("reviewed").default(0), // 0=unreviewed, 1=approved, 2=rejected
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (table) => ({
    fromNodeIdx: index("idx_context_edges_from_node").on(table.fromNodeId),
    toNodeIdx: index("idx_context_edges_to_node").on(table.toNodeId),
    sourceEvidenceIdx: index("idx_context_edges_source_evidence").on(table.sourceEvidenceId),
  })
);

export const contextSnapshots = sqliteTable(
  "context_snapshots",
  {
    id: text("id").primaryKey(),
    // cross-BC: no FK reference to discoveries
    discoveryId: text("discovery_id").notNull(),
    stage: text("stage").notNull(),
    snapshotData: text("snapshot_data", { mode: "json" }).$type<{
      nodes: Array<Record<string, unknown>>;
      edges: Array<Record<string, unknown>>;
    }>(),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (table) => ({
    discoveryIdIdx: index("idx_context_snapshots_discovery_id").on(table.discoveryId),
  })
);

export const evidenceDuplicateCandidates = sqliteTable(
  "evidence_duplicate_candidates",
  {
    id: text("id").primaryKey(),
    // cross-BC: no FK reference to evidence
    evidenceId1: text("evidence_id_1").notNull(),
    evidenceId2: text("evidence_id_2").notNull(),
    similarityScore: integer("similarity_score").notNull(), // 0~100
    reason: text("reason"),
    reviewed: integer("reviewed").notNull().default(0),
    reviewedAt: integer("reviewed_at", { mode: "timestamp" }),
    reviewedBy: text("reviewed_by").references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
  },
  (table) => ({
    evidenceId1Idx: index("idx_evidence_dup_evidence_id_1").on(table.evidenceId1),
    evidenceId2Idx: index("idx_evidence_dup_evidence_id_2").on(table.evidenceId2),
    reviewedIdx: index("idx_evidence_dup_reviewed").on(table.reviewed),
  })
);

// ============================================================================
// TYPES
// ============================================================================

export type OntologyType = typeof ontologyTypes.$inferSelect;
export type NewOntologyType = typeof ontologyTypes.$inferInsert;

export type ContextNode = typeof contextNodes.$inferSelect;
export type NewContextNode = typeof contextNodes.$inferInsert;

export type ContextEdge = typeof contextEdges.$inferSelect;
export type NewContextEdge = typeof contextEdges.$inferInsert;

export type ContextSnapshot = typeof contextSnapshots.$inferSelect;
export type NewContextSnapshot = typeof contextSnapshots.$inferInsert;

export type EvidenceDuplicateCandidate = typeof evidenceDuplicateCandidates.$inferSelect;
export type NewEvidenceDuplicateCandidate = typeof evidenceDuplicateCandidates.$inferInsert;
