/**
 * LabService 단위 테스트 (실 DB 기반)
 *
 * 대상: app/features/lab/service/lab.service.ts
 * 14개 메서드 전체 커버
 */
import { describe, it, expect, beforeEach, vi } from "vitest";
import { createTestDb, type TestDB } from "tests/helpers/db";
import type { DB } from "~/db";
import { LabService } from "~/features/lab/service/lab.service";
import {
  users,
  tenants,
  tenantMembers,
  discoveries,
  contextNodes,
  contextEdges,
  ontologyTypes,
  methodPacks,
} from "~/db";
import { eq } from "drizzle-orm";

// ─── Mocks ──────────────────────────────────────────────────────────────

vi.mock("~/lib/ontology/analyzer", () => ({
  detectPatterns: vi.fn().mockResolvedValue([
    { type: "co-occurrence", nodes: ["a", "b"], count: 3 },
  ]),
  detectContradictions: vi.fn().mockResolvedValue([
    { nodeA: "a", nodeB: "b", reason: "conflict" },
  ]),
  analyzeCentrality: vi.fn().mockResolvedValue([
    { nodeId: "n1", label: "Entity A", score: 0.9 },
  ]),
}));

import { detectPatterns, detectContradictions, analyzeCentrality } from "~/lib/ontology/analyzer";

// ─── 상수 ───────────────────────────────────────────────────────────────

const TENANT_ID = "t-lab-test";
const TENANT_OTHER = "t-lab-other";
const USER_ID = "user-lab-1";
const DISC_ID = "disc-lab-1";

// ─── Helpers ────────────────────────────────────────────────────────────

function asDB(d: TestDB) {
  return d as unknown as DB;
}

function seedBase(db: TestDB) {
  db.insert(users)
    .values({ id: USER_ID, email: "lab@test.com", name: "Lab User", role: "admin" })
    .run();
  db.insert(tenants)
    .values([
      { id: TENANT_ID, name: "Lab Tenant", slug: "lab-test", ownerUserId: USER_ID },
      { id: TENANT_OTHER, name: "Other", slug: "lab-other", ownerUserId: USER_ID },
    ])
    .run();
  db.insert(tenantMembers)
    .values({ id: "tm-lab-1", tenantId: TENANT_ID, userId: USER_ID })
    .run();
  db.insert(discoveries)
    .values({
      id: DISC_ID,
      title: "Lab Discovery",
      seedSummary: "test",
      sourceType: "article",
      status: "DISCOVERY",
      ownerId: USER_ID,
      tenantId: TENANT_ID,
    })
    .run();
}

function seedOntologyTypes(db: TestDB) {
  db.insert(ontologyTypes)
    .values([
      { id: "type-company", nameKo: "기업", domain: "business", color: "#FF0000", icon: "building" },
      { id: "type-tech", nameKo: "기술", domain: "ecosystem", color: "#00FF00", icon: "cpu" },
    ])
    .run();
}

function seedNodes(db: TestDB, count: number, overrides: Partial<{ autoGenerated: number; reviewed: number }> = {}) {
  const nodes = Array.from({ length: count }, (_, i) => ({
    id: `node-${i}`,
    discoveryId: DISC_ID,
    label: `Entity ${i}`,
    ontologyTypeId: "type-company",
    confidence: 0.8,
    autoGenerated: overrides.autoGenerated ?? 1,
    reviewed: overrides.reviewed ?? 0,
  }));
  db.insert(contextNodes).values(nodes).run();
  return nodes;
}

function seedEdges(db: TestDB, nodeIds: string[], overrides: Partial<{ autoGenerated: number; reviewed: number }> = {}) {
  const edges: Array<{
    id: string;
    fromNodeId: string;
    toNodeId: string;
    relationType: string;
    strength: number;
    autoGenerated: number;
    reviewed: number;
  }> = [];
  for (let i = 0; i < nodeIds.length - 1; i++) {
    edges.push({
      id: `edge-${i}`,
      fromNodeId: nodeIds[i],
      toNodeId: nodeIds[i + 1],
      relationType: "related_to",
      strength: 0.7,
      autoGenerated: overrides.autoGenerated ?? 1,
      reviewed: overrides.reviewed ?? 0,
    });
  }
  if (edges.length > 0) db.insert(contextEdges).values(edges).run();
  return edges;
}

// ─── Setup ──────────────────────────────────────────────────────────────

let db: TestDB;
let service: LabService;

beforeEach(() => {
  db = createTestDb();
  service = new LabService(asDB(db));
  vi.clearAllMocks();
  seedBase(db);
  seedOntologyTypes(db);
});

// ─── Tests ──────────────────────────────────────────────────────────────

describe("LabService", () => {
  // ══════════════════════════════════════════════
  // Stats
  // ══════════════════════════════════════════════
  describe("getStats", () => {
    it("노드/엣지/글로벌엔티티/미검토 카운트 정확성", async () => {
      const nodes = seedNodes(db, 3);
      seedEdges(db, nodes.map((n) => n.id));

      // 1개 노드에 globalEntityId 설정
      db.update(contextNodes)
        .set({ globalEntityId: "global-1" })
        .where(eq(contextNodes.id, "node-0"))
        .run();

      const stats = await service.getStats({ tenantId: TENANT_ID });

      expect(stats.nodes).toBe(3);
      expect(stats.edges).toBe(2);
      expect(stats.globalEntities).toBe(1);
      expect(stats.unreviewedNodes).toBe(3); // 전부 autoGenerated=1, reviewed=0
      expect(stats.unreviewedEdges).toBe(2);
    });

    it("빈 데이터 시 모두 0", async () => {
      const stats = await service.getStats({ tenantId: TENANT_ID });

      expect(stats.nodes).toBe(0);
      expect(stats.edges).toBe(0);
      expect(stats.globalEntities).toBe(0);
      expect(stats.unreviewedNodes).toBe(0);
      expect(stats.unreviewedEdges).toBe(0);
    });
  });

  // ══════════════════════════════════════════════
  // Graph
  // ══════════════════════════════════════════════
  describe("Graph", () => {
    it("getGraphNodes — 테넌트별 필터링 + rejected 제외", async () => {
      seedNodes(db, 3);
      // node-2를 rejected로
      db.update(contextNodes).set({ reviewed: 2 }).where(eq(contextNodes.id, "node-2")).run();

      const nodes = await service.getGraphNodes({ tenantId: TENANT_ID });
      expect(nodes).toHaveLength(2);
      expect(nodes.every((n) => n.id !== "node-2")).toBe(true);
    });

    it("getGraphEdges — rejected 제외", async () => {
      const nodes = seedNodes(db, 3);
      seedEdges(db, nodes.map((n) => n.id));
      // edge-0을 rejected
      db.update(contextEdges).set({ reviewed: 2 }).where(eq(contextEdges.id, "edge-0")).run();

      const edges = await service.getGraphEdges();
      expect(edges).toHaveLength(1);
      expect(edges[0].id).toBe("edge-1");
    });
  });

  // ══════════════════════════════════════════════
  // Nodes
  // ══════════════════════════════════════════════
  describe("Nodes", () => {
    it("getRecentNodes — autoGenerated=1만, limit 적용", async () => {
      seedNodes(db, 3, { autoGenerated: 1 });
      // 수동 노드 추가
      db.insert(contextNodes)
        .values({
          id: "node-manual",
          discoveryId: DISC_ID,
          label: "Manual",
          ontologyTypeId: "type-company",
          autoGenerated: 0,
          reviewed: 1,
        })
        .run();

      const recent = await service.getRecentNodes({ tenantId: TENANT_ID, limit: 2 });
      expect(recent).toHaveLength(2);
      expect(recent.every((n) => n.id !== "node-manual")).toBe(true);
    });

    it("getAnalysisNodes — rejected 제외, limit 적용", async () => {
      seedNodes(db, 5);
      db.update(contextNodes).set({ reviewed: 2 }).where(eq(contextNodes.id, "node-4")).run();

      const nodes = await service.getAnalysisNodes({ tenantId: TENANT_ID, limit: 10 });
      expect(nodes).toHaveLength(4);
    });
  });

  // ══════════════════════════════════════════════
  // Review Queue
  // ══════════════════════════════════════════════
  describe("Review Queue", () => {
    it("getUnreviewedNodes — autoGenerated=1 AND reviewed=0만", async () => {
      seedNodes(db, 3, { autoGenerated: 1, reviewed: 0 });
      db.insert(contextNodes)
        .values({
          id: "node-approved",
          discoveryId: DISC_ID,
          label: "Approved",
          ontologyTypeId: "type-company",
          autoGenerated: 1,
          reviewed: 1,
        })
        .run();

      const unreviewedNodes = await service.getUnreviewedNodes({ tenantId: TENANT_ID });
      expect(unreviewedNodes).toHaveLength(3);
    });

    it("getUnreviewedEdges — autoGenerated=1 AND reviewed=0만", async () => {
      const nodes = seedNodes(db, 3);
      seedEdges(db, nodes.map((n) => n.id), { autoGenerated: 1, reviewed: 0 });
      // 하나 승인
      db.update(contextEdges).set({ reviewed: 1 }).where(eq(contextEdges.id, "edge-0")).run();

      const unreviewedEdges = await service.getUnreviewedEdges();
      expect(unreviewedEdges).toHaveLength(1);
    });

    it("getReviewQueueData — 통합 데이터 반환", async () => {
      seedNodes(db, 2);
      const data = await service.getReviewQueueData({ tenantId: TENANT_ID });

      expect(data).toHaveProperty("unreviewedNodes");
      expect(data).toHaveProperty("unreviewedEdges");
      expect(data).toHaveProperty("types");
      expect(data.types.length).toBeGreaterThanOrEqual(2); // type-company, type-tech
    });
  });

  // ══════════════════════════════════════════════
  // Review Actions
  // ══════════════════════════════════════════════
  describe("Review Actions", () => {
    beforeEach(() => {
      seedNodes(db, 2);
      const nodeIds = ["node-0", "node-1"];
      seedEdges(db, nodeIds);
    });

    it("reviewNode approve — reviewed 0→1", async () => {
      const ok = await service.reviewNode({ id: "node-0", action: "approve" });
      expect(ok).toBe(true);

      const [row] = await db.select().from(contextNodes).where(eq(contextNodes.id, "node-0"));
      expect(row.reviewed).toBe(1);
    });

    it("reviewNode reject — reviewed 0→2", async () => {
      const ok = await service.reviewNode({ id: "node-0", action: "reject" });
      expect(ok).toBe(true);

      const [row] = await db.select().from(contextNodes).where(eq(contextNodes.id, "node-0"));
      expect(row.reviewed).toBe(2);
    });

    it("reviewNode edit — label/typeId 변경 + reviewed=1", async () => {
      const ok = await service.reviewNode({
        id: "node-0",
        action: "edit",
        editedLabel: "수정된 이름",
        editedTypeId: "type-tech",
      });
      expect(ok).toBe(true);

      const [row] = await db.select().from(contextNodes).where(eq(contextNodes.id, "node-0"));
      expect(row.label).toBe("수정된 이름");
      expect(row.ontologyTypeId).toBe("type-tech");
      expect(row.reviewed).toBe(1);
    });

    it("reviewNode — 존재하지 않는 ID → false", async () => {
      const ok = await service.reviewNode({ id: "nope", action: "approve" });
      expect(ok).toBe(false);
    });

    it("reviewEdge approve — reviewed 0→1", async () => {
      const ok = await service.reviewEdge({ id: "edge-0", action: "approve" });
      expect(ok).toBe(true);

      const [row] = await db.select().from(contextEdges).where(eq(contextEdges.id, "edge-0"));
      expect(row.reviewed).toBe(1);
    });

    it("reviewEdge reject — reviewed 0→2", async () => {
      const ok = await service.reviewEdge({ id: "edge-0", action: "reject" });
      expect(ok).toBe(true);

      const [row] = await db.select().from(contextEdges).where(eq(contextEdges.id, "edge-0"));
      expect(row.reviewed).toBe(2);
    });

    it("reviewEdge — 존재하지 않는 ID → false", async () => {
      const ok = await service.reviewEdge({ id: "nope", action: "approve" });
      expect(ok).toBe(false);
    });
  });

  // ══════════════════════════════════════════════
  // Ontology Types & Method Packs
  // ══════════════════════════════════════════════
  describe("Ontology Types & Method Packs", () => {
    it("getOntologyTypes — 전체 목록 반환", async () => {
      const types = await service.getOntologyTypes();
      // 마이그레이션 시드 + 테스트 시드 포함
      expect(types.length).toBeGreaterThanOrEqual(2);
      expect(types.map((t) => t.nameKo)).toContain("기업");
    });

    it("getMethodPacks — 전체 목록 반환", async () => {
      // method_packs 시드 (0008 마이그레이션에 초기 데이터 있을 수 있음)
      const packs = await service.getMethodPacks();
      expect(Array.isArray(packs)).toBe(true);
    });
  });

  // ══════════════════════════════════════════════
  // 통합 데이터
  // ══════════════════════════════════════════════
  describe("통합 데이터", () => {
    it("getOverviewData — stats + graphNodes + graphEdges(유효만) + recentNodes + types", async () => {
      const nodes = seedNodes(db, 3);
      seedEdges(db, nodes.map((n) => n.id));

      // node-2를 rejected로 설정하여 그래프에서 제외
      db.update(contextNodes).set({ reviewed: 2 }).where(eq(contextNodes.id, "node-2")).run();

      const data = await service.getOverviewData({ tenantId: TENANT_ID });

      expect(data.stats.nodes).toBe(3); // 전체 카운트
      expect(data.graphNodes).toHaveLength(2); // rejected 제외
      // node-2가 빠지면 edge-1 (node-1→node-2)은 orphan
      expect(data.graphEdges).toHaveLength(1); // 유효 엣지만
      expect(data.types.length).toBeGreaterThanOrEqual(2);
    });

    it("getAnalysisData — nodes + types + tenantId", async () => {
      seedNodes(db, 2);

      const data = await service.getAnalysisData({ tenantId: TENANT_ID });

      expect(data.nodes).toHaveLength(2);
      expect(data.types.length).toBeGreaterThanOrEqual(2);
      expect(data.tenantId).toBe(TENANT_ID);
    });

    it("getInsightSummary — 노드 5개 미만이면 hasData=false", async () => {
      seedNodes(db, 3);

      const summary = await service.getInsightSummary({ tenantId: TENANT_ID });

      expect(summary.hasData).toBe(false);
      expect(summary.patterns).toEqual([]);
      expect(vi.mocked(detectPatterns)).not.toHaveBeenCalled();
    });

    it("getInsightSummary — 노드 5개 이상이면 analyzer 호출 + hasData=true", async () => {
      seedNodes(db, 6);

      const summary = await service.getInsightSummary({ tenantId: TENANT_ID });

      expect(summary.hasData).toBe(true);
      expect(summary.patterns).toHaveLength(1);
      expect(summary.contradictions).toHaveLength(1);
      expect(summary.topEntities).toHaveLength(1);
      expect(vi.mocked(detectPatterns)).toHaveBeenCalled();
      expect(vi.mocked(detectContradictions)).toHaveBeenCalled();
      expect(vi.mocked(analyzeCentrality)).toHaveBeenCalled();
    });
  });
});
