/**
 * LLM-based Ontology Entity Extractor
 *
 * Evidence 텍스트에서 엔티티와 관계를 자동 추출하여
 * contextNodes / contextEdges 에 저장한다.
 */

import { eq, and, sql, or, isNull } from "drizzle-orm";
import type { DrizzleD1Database } from "drizzle-orm/d1";
import { evidence, contextNodes, contextEdges, ontologyTypes, discoveries } from "~/db/schema";
import { callLLM } from "~/lib/ai";
import { matchGlobalEntitiesBatch } from "./matcher";

// --- Types ---

interface ExtractedEntity {
  label: string;
  ontologyTypeId: string;
  confidence: number;
}

interface ExtractedRelation {
  fromLabel: string;
  toLabel: string;
  relationType: "supports" | "contradicts" | "causes" | "relates_to" | "depends_on";
  strength: number;
  confidence: number;
}

interface LLMExtractionResult {
  entities: ExtractedEntity[];
  relations: ExtractedRelation[];
}

export interface ExtractionResult {
  evidenceProcessed: number;
  nodesCreated: number;
  edgesCreated: number;
  globalEntitiesMatched: number;
  errors: string[];
}

const VALID_RELATION_TYPES = ["supports", "contradicts", "causes", "relates_to", "depends_on"];

const EXTRACTION_SYSTEM_PROMPT = `당신은 비즈니스/전략 온톨로지 전문가입니다.
주어진 Evidence 텍스트에서 핵심 엔티티(개념)와 관계를 추출하세요.

## 규칙
1. 엔티티는 구체적이고 재사용 가능한 개념이어야 합니다 (예: "ESG 시장", "탄소중립 정책")
2. 일반적이거나 모호한 개념은 제외하세요 (예: "성장", "변화")
3. ontologyTypeId는 반드시 제공된 목록에서 선택하세요
4. 관계의 strength는 0.0~1.0 사이 값입니다 (1.0 = 매우 강한 관계)
5. confidence는 추출 확신도입니다 (0.0~1.0)
6. 기존 노드 목록에 유사한 엔티티가 있으면 정확히 같은 label을 사용하세요

## 응답 형식 (JSON만 출력)
{
  "entities": [
    { "label": "엔티티명", "ontologyTypeId": "ONT-XX", "confidence": 0.95 }
  ],
  "relations": [
    { "fromLabel": "엔티티A", "toLabel": "엔티티B", "relationType": "supports", "strength": 0.8, "confidence": 0.85 }
  ]
}`;

// --- Core Functions ---

/**
 * 단일 Evidence에서 엔티티/관계 추출
 */
export async function extractFromEvidence(
  db: DrizzleD1Database<Record<string, unknown>>,
  apiKey: string,
  ev: { id: string; content: string; discoveryId: string },
  existingNodes: Array<{ label: string; ontologyTypeId: string | null }>,
  typeList: Array<{ id: string; nameKo: string; domain: string }>,
): Promise<{ nodesCreated: number; edgesCreated: number; globalMatched: number }> {
  // 1. LLM 호출
  const extraction = await callExtractionLLM(apiKey, ev.content, existingNodes, typeList);
  if (!extraction || extraction.entities.length === 0) {
    return { nodesCreated: 0, edgesCreated: 0, globalMatched: 0 };
  }

  // 2. 신뢰도 필터링 (0.5 미만 무시)
  const validEntities = extraction.entities.filter((e) => e.confidence >= 0.5);
  if (validEntities.length === 0) {
    return { nodesCreated: 0, edgesCreated: 0, globalMatched: 0 };
  }

  // 3. 글로벌 엔티티 매칭 (배치)
  const matchResults = await matchGlobalEntitiesBatch(
    db,
    validEntities.map((e) => ({ label: e.label, ontologyTypeId: e.ontologyTypeId })),
  );

  // 4. 노드 생성
  //    ≥ 0.8: 자동 생성 + 검토 큐 (그래프 참여 가능 — 엣지 생성 대상)
  //    0.5~0.8: 검토 큐에만 등록 (그래프 미참여 — 엣지 생성 제외)
  const nodeMap = new Map<string, string>(); // label → nodeId (≥ 0.8만 등록)
  let nodesCreated = 0;
  let globalMatched = 0;

  for (const entity of validEntities) {
    if (entity.confidence < 0.5) continue; // 0.5 미만은 무시

    const key = `${entity.label}::${entity.ontologyTypeId}`;
    const matchResult = matchResults.get(key);
    if (!matchResult) continue;

    if (!matchResult.isNew) globalMatched++;

    // 같은 Discovery에 동일 label+type 노드가 있으면 건너뛰기
    const existing = await db
      .select({ id: contextNodes.id })
      .from(contextNodes)
      .where(
        and(
          eq(contextNodes.discoveryId, ev.discoveryId),
          eq(contextNodes.label, entity.label),
          eq(contextNodes.ontologyTypeId, entity.ontologyTypeId),
        ),
      )
      .limit(1);

    if (existing.length > 0) {
      // ≥ 0.8만 그래프에 참여 (엣지 생성 대상)
      if (entity.confidence >= 0.8) {
        nodeMap.set(entity.label, existing[0].id);
      }
      continue;
    }

    const nodeId = crypto.randomUUID();
    await db.insert(contextNodes).values({
      id: nodeId,
      discoveryId: ev.discoveryId,
      label: entity.label,
      ontologyTypeId: entity.ontologyTypeId,
      sourceEvidenceId: ev.id,
      globalEntityId: matchResult.globalEntityId,
      confidence: entity.confidence,
      autoGenerated: 1,
      reviewed: 0,
    });

    // ≥ 0.8: 그래프에 참여 (엣지 생성 대상)
    // 0.5~0.8: 검토 큐에만 존재 (엣지 미생성)
    if (entity.confidence >= 0.8) {
      nodeMap.set(entity.label, nodeId);
    }
    nodesCreated++;
  }

  // 5. 엣지 생성
  let edgesCreated = 0;
  for (const rel of extraction.relations) {
    if (rel.confidence < 0.5) continue;
    if (!VALID_RELATION_TYPES.includes(rel.relationType)) continue;

    const fromId = nodeMap.get(rel.fromLabel);
    const toId = nodeMap.get(rel.toLabel);
    if (!fromId || !toId || fromId === toId) continue;

    const edgeId = crypto.randomUUID();
    await db.insert(contextEdges).values({
      id: edgeId,
      fromNodeId: fromId,
      toNodeId: toId,
      relationType: rel.relationType,
      strength: Math.round(rel.strength * 100),
      sourceEvidenceId: ev.id,
      confidence: rel.confidence,
      autoGenerated: 1,
      reviewed: 0,
    });
    edgesCreated++;
  }

  return { nodesCreated, edgesCreated, globalMatched };
}

/**
 * LLM 호출 — 엔티티/관계 추출
 */
async function callExtractionLLM(
  apiKey: string,
  content: string,
  existingNodes: Array<{ label: string; ontologyTypeId: string | null }>,
  typeList: Array<{ id: string; nameKo: string; domain: string }>,
): Promise<LLMExtractionResult | null> {
  const typeListStr = typeList
    .map((t) => `${t.id}: ${t.nameKo} (${t.domain})`)
    .join("\n");

  const existingStr =
    existingNodes.length > 0
      ? existingNodes.map((n) => `- ${n.label} (${n.ontologyTypeId})`).join("\n")
      : "(없음)";

  const userMessage = `## Evidence 텍스트
${content}

## 사용 가능한 온톨로지 타입
${typeListStr}

## 기존 엔티티 노드
${existingStr}

위 Evidence에서 엔티티와 관계를 추출하세요. JSON만 출력하세요.`;

  // 최대 2회 재시도 (설계: §4.3 — JSON 파싱 실패 시)
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const response = await callLLM(apiKey, {
        model: "claude-haiku-4-5-20251001",
        max_tokens: 2048,
        temperature: 0.1,
        system:
          attempt === 0
            ? EXTRACTION_SYSTEM_PROMPT
            : EXTRACTION_SYSTEM_PROMPT + "\n\n중요: 반드시 유효한 JSON만 출력하세요. 다른 텍스트를 포함하지 마세요.",
        messages: [{ role: "user", content: userMessage }],
      });

      const textBlock = response.content.find((b) => b.type === "text");
      if (!textBlock?.text) {
        if (attempt < 2) continue;
        return null;
      }

      const jsonMatch = textBlock.text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        if (attempt < 2) continue;
        return null;
      }

      const parsed = JSON.parse(jsonMatch[0]) as LLMExtractionResult;

      // 기본 검증
      if (!Array.isArray(parsed.entities)) parsed.entities = [];
      if (!Array.isArray(parsed.relations)) parsed.relations = [];

      return parsed;
    } catch {
      if (attempt >= 2) return null;
    }
  }
  return null;
}

/**
 * 배치 추출 — Cron에서 호출
 */
export async function extractOntologyBatch(
  db: DrizzleD1Database<Record<string, unknown>>,
  apiKey: string,
  tenantId: string,
  batchSize = 5,
): Promise<ExtractionResult> {
  const result: ExtractionResult = {
    evidenceProcessed: 0,
    nodesCreated: 0,
    edgesCreated: 0,
    globalEntitiesMatched: 0,
    errors: [],
  };

  try {
    // 1. Stale evidence 조회 (테넌트 격리)
    const staleEvidence = await db
      .select({
        id: evidence.id,
        content: evidence.content,
        discoveryId: evidence.discoveryId,
      })
      .from(evidence)
      .innerJoin(discoveries, eq(evidence.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, tenantId),
          or(
            isNull(evidence.ontologyExtractedAt),
            sql`${evidence.ontologyExtractedAt} < ${evidence.createdAt}`,
          ),
        ),
      )
      .limit(batchSize);

    if (staleEvidence.length === 0) return result;

    // 2. 온톨로지 타입 목록
    const typeList = await db
      .select({ id: ontologyTypes.id, nameKo: ontologyTypes.nameKo, domain: ontologyTypes.domain })
      .from(ontologyTypes);

    // 3. 각 Evidence 처리
    for (const ev of staleEvidence) {
      try {
        // 해당 Discovery의 기존 노드
        const existingNodes = await db
          .select({ label: contextNodes.label, ontologyTypeId: contextNodes.ontologyTypeId })
          .from(contextNodes)
          .where(eq(contextNodes.discoveryId, ev.discoveryId));

        const extracted = await extractFromEvidence(db, apiKey, ev, existingNodes, typeList);

        result.nodesCreated += extracted.nodesCreated;
        result.edgesCreated += extracted.edgesCreated;
        result.globalEntitiesMatched += extracted.globalMatched;
        result.evidenceProcessed++;

        // 추출 완료 마킹
        await db
          .update(evidence)
          .set({ ontologyExtractedAt: new Date() })
          .where(eq(evidence.id, ev.id));
      } catch (err) {
        result.errors.push(`evidence ${ev.id}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }
  } catch (err) {
    result.errors.push(`batch: ${err instanceof Error ? err.message : String(err)}`);
  }

  return result;
}
