import { eq, and, ne, sql } from "drizzle-orm";
import type { DB } from "~/db";
import {
  contextNodes,
  contextEdges,
  ontologyTypes,
  discoveries,
  methodPacks,
} from "~/db/schema";
import {
  detectPatterns,
  detectContradictions,
  analyzeCentrality,
} from "~/lib/ontology/analyzer";

// ============================================================================
// Types
// ============================================================================

interface TenantParams {
  tenantId: string;
}

interface ReviewNodeInput {
  id: string;
  action: "approve" | "reject" | "edit";
  editedLabel?: string;
  editedTypeId?: string;
}

interface ReviewEdgeInput {
  id: string;
  action: "approve" | "reject";
}

// ============================================================================
// Service
// ============================================================================

export class LabService {
  constructor(private db: DB) {}

  // ---------- Stats ----------

  /** 개요 통계 (노드/엣지/글로벌/미검토) */
  async getStats(params: TenantParams) {
    const [nodeCount] = await this.db
      .select({ count: sql<number>`COUNT(*)` })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(eq(discoveries.tenantId, params.tenantId));

    const [edgeCount] = await this.db
      .select({ count: sql<number>`COUNT(*)` })
      .from(contextEdges)
      .innerJoin(contextNodes, eq(contextEdges.fromNodeId, contextNodes.id))
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(eq(discoveries.tenantId, params.tenantId));

    const [globalEntityCount] = await this.db
      .select({
        count: sql<number>`COUNT(DISTINCT ${contextNodes.globalEntityId})`,
      })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, params.tenantId),
          sql`${contextNodes.globalEntityId} IS NOT NULL`,
        ),
      );

    const [unreviewedNodeCount] = await this.db
      .select({ count: sql<number>`COUNT(*)` })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, params.tenantId),
          eq(contextNodes.autoGenerated, 1),
          eq(contextNodes.reviewed, 0),
        ),
      );

    const [unreviewedEdgeCount] = await this.db
      .select({ count: sql<number>`COUNT(*)` })
      .from(contextEdges)
      .where(
        and(
          eq(contextEdges.autoGenerated, 1),
          eq(contextEdges.reviewed, 0),
        ),
      );

    return {
      nodes: nodeCount.count,
      edges: edgeCount.count,
      globalEntities: globalEntityCount.count,
      unreviewedNodes: unreviewedNodeCount.count,
      unreviewedEdges: unreviewedEdgeCount.count,
    };
  }

  // ---------- Graph ----------

  /** 그래프 노드 조회 (rejected 제외) */
  async getGraphNodes(params: TenantParams) {
    return this.db
      .select({
        id: contextNodes.id,
        label: contextNodes.label,
        ontologyTypeId: contextNodes.ontologyTypeId,
        sourceEvidenceId: contextNodes.sourceEvidenceId,
        metadata: contextNodes.metadata,
      })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, params.tenantId),
          sql`${contextNodes.reviewed} != 2`,
        ),
      );
  }

  /** 그래프 엣지 조회 (rejected 제외) */
  async getGraphEdges() {
    return this.db
      .select({
        id: contextEdges.id,
        fromNodeId: contextEdges.fromNodeId,
        toNodeId: contextEdges.toNodeId,
        relationType: contextEdges.relationType,
        strength: contextEdges.strength,
        sourceEvidenceId: contextEdges.sourceEvidenceId,
      })
      .from(contextEdges)
      .where(sql`${contextEdges.reviewed} != 2`);
  }

  // ---------- Nodes ----------

  /** 최근 자동 생성 노드 조회 */
  async getRecentNodes(params: TenantParams & { limit?: number }) {
    return this.db
      .select({
        id: contextNodes.id,
        label: contextNodes.label,
        ontologyTypeId: contextNodes.ontologyTypeId,
        confidence: contextNodes.confidence,
        globalEntityId: contextNodes.globalEntityId,
        createdAt: contextNodes.createdAt,
      })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, params.tenantId),
          eq(contextNodes.autoGenerated, 1),
        ),
      )
      .orderBy(sql`${contextNodes.createdAt} DESC`)
      .limit(params.limit ?? 5);
  }

  /** 분석용 노드 조회 (rejected 제외) */
  async getAnalysisNodes(params: TenantParams & { limit?: number }) {
    return this.db
      .select({
        id: contextNodes.id,
        label: contextNodes.label,
        ontologyTypeId: contextNodes.ontologyTypeId,
        discoveryId: contextNodes.discoveryId,
        globalEntityId: contextNodes.globalEntityId,
      })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, params.tenantId),
          ne(contextNodes.reviewed, 2),
        ),
      )
      .limit(params.limit ?? 200);
  }

  // ---------- Review ----------

  /** 미검토 노드 목록 조회 */
  async getUnreviewedNodes(params: TenantParams & { limit?: number }) {
    return this.db
      .select({
        id: contextNodes.id,
        label: contextNodes.label,
        ontologyTypeId: contextNodes.ontologyTypeId,
        confidence: contextNodes.confidence,
        discoveryId: contextNodes.discoveryId,
        globalEntityId: contextNodes.globalEntityId,
        createdAt: contextNodes.createdAt,
      })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, params.tenantId),
          eq(contextNodes.autoGenerated, 1),
          eq(contextNodes.reviewed, 0),
        ),
      )
      .orderBy(sql`${contextNodes.createdAt} DESC`)
      .limit(params.limit ?? 50);
  }

  /** 미검토 엣지 목록 조회 */
  async getUnreviewedEdges(params: { limit?: number } = {}) {
    return this.db
      .select({
        id: contextEdges.id,
        fromNodeId: contextEdges.fromNodeId,
        toNodeId: contextEdges.toNodeId,
        relationType: contextEdges.relationType,
        strength: contextEdges.strength,
        confidence: contextEdges.confidence,
        createdAt: contextEdges.createdAt,
      })
      .from(contextEdges)
      .where(
        and(
          eq(contextEdges.autoGenerated, 1),
          eq(contextEdges.reviewed, 0),
        ),
      )
      .orderBy(sql`${contextEdges.createdAt} DESC`)
      .limit(params.limit ?? 50);
  }

  /** 노드 리뷰 (approve/reject/edit) */
  async reviewNode(input: ReviewNodeInput): Promise<boolean> {
    const node = await this.db
      .select({ id: contextNodes.id })
      .from(contextNodes)
      .where(eq(contextNodes.id, input.id))
      .limit(1);

    if (node.length === 0) return false;

    const updates: Record<string, unknown> = {
      reviewed: input.action === "reject" ? 2 : 1,
    };

    if (input.action === "edit") {
      if (input.editedLabel) updates.label = input.editedLabel;
      if (input.editedTypeId) updates.ontologyTypeId = input.editedTypeId;
    }

    await this.db
      .update(contextNodes)
      .set(updates)
      .where(eq(contextNodes.id, input.id));

    return true;
  }

  /** 엣지 리뷰 (approve/reject) */
  async reviewEdge(input: ReviewEdgeInput): Promise<boolean> {
    const edge = await this.db
      .select({ id: contextEdges.id })
      .from(contextEdges)
      .where(eq(contextEdges.id, input.id))
      .limit(1);

    if (edge.length === 0) return false;

    await this.db
      .update(contextEdges)
      .set({ reviewed: input.action === "reject" ? 2 : 1 })
      .where(eq(contextEdges.id, input.id));

    return true;
  }

  // ---------- Ontology Types ----------

  /** 온톨로지 타입 전체 조회 */
  async getOntologyTypes() {
    return this.db.select().from(ontologyTypes);
  }

  // ---------- Method Packs ----------

  /** 방법론 팩 전체 조회 */
  async getMethodPacks() {
    return this.db.select().from(methodPacks);
  }

  // ---------- 통합 데이터 ----------

  /** lab._index.tsx loader용 통합 데이터 */
  async getOverviewData(params: TenantParams) {
    const [stats, graphNodes, allEdges, recentNodes, types] = await Promise.all(
      [
        this.getStats(params),
        this.getGraphNodes(params),
        this.getGraphEdges(),
        this.getRecentNodes(params),
        this.getOntologyTypes(),
      ],
    );

    // 유효 엣지만 필터 (양쪽 노드가 존재하는 것만)
    const nodeIds = new Set(graphNodes.map((n) => n.id));
    const graphEdges = allEdges.filter(
      (e) => nodeIds.has(e.fromNodeId) && nodeIds.has(e.toNodeId),
    );

    return { stats, graphNodes, graphEdges, recentNodes, types };
  }

  /** lab.analysis.tsx loader용 데이터 */
  async getAnalysisData(params: TenantParams) {
    const [nodes, types] = await Promise.all([
      this.getAnalysisNodes(params),
      this.getOntologyTypes(),
    ]);
    return { nodes, types, tenantId: params.tenantId };
  }

  /** 인사이트 요약 (패턴·모순·중심 엔티티 top-N) */
  async getInsightSummary(params: TenantParams): Promise<{
    patterns: unknown[];
    contradictions: unknown[];
    topEntities: unknown[];
    hasData: boolean;
  }> {
    const [nodeCountRow] = await this.db
      .select({ count: sql<number>`COUNT(*)` })
      .from(contextNodes)
      .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
      .where(
        and(
          eq(discoveries.tenantId, params.tenantId),
          ne(contextNodes.reviewed, 2),
        ),
      );

    if (nodeCountRow.count < 5) {
      return { patterns: [], contradictions: [], topEntities: [], hasData: false };
    }

    const analyzerDb = this.db as unknown as Parameters<typeof detectPatterns>[0];
    const [patterns, contradictions, topEntities] = await Promise.all([
      detectPatterns(analyzerDb, params.tenantId),
      detectContradictions(analyzerDb, params.tenantId),
      analyzeCentrality(analyzerDb, params.tenantId),
    ]);

    return {
      patterns: patterns.slice(0, 3),
      contradictions: contradictions.slice(0, 3),
      topEntities: topEntities.slice(0, 5),
      hasData: true,
    };
  }

  /** lab.review.tsx loader용 데이터 */
  async getReviewQueueData(params: TenantParams) {
    const [unreviewedNodes, unreviewedEdges, types] = await Promise.all([
      this.getUnreviewedNodes(params),
      this.getUnreviewedEdges(),
      this.getOntologyTypes(),
    ]);
    return { unreviewedNodes, unreviewedEdges, types };
  }
}
