import type { LoaderFunctionArgs } from "@remix-run/cloudflare";
import { json } from "@remix-run/cloudflare";
import { useLoaderData } from "@remix-run/react";
import { eq, and, sql } from "drizzle-orm";
import { getDb } from "~/db";
import { contextNodes, contextEdges, discoveries, ontologyTypes } from "~/db/schema";
import { getSessionContext } from "~/lib/auth/session.server";
import { Card, CardContent } from "~/components/ui/Card";
import { Badge } from "~/components/ui/Badge";

export async function loader({ request, context }: LoaderFunctionArgs) {
  const env = context.cloudflare.env as unknown as {
    DB: D1Database;
    SESSION_SECRET: string;
  };
  const db = getDb(env.DB);
  const ctx = await getSessionContext(request, db, env.SESSION_SECRET);
  if (!ctx) throw new Response("Unauthorized", { status: 401 });

  // 전체 노드 수
  const [nodeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(eq(discoveries.tenantId, ctx.tenantId));

  // 전체 엣지 수
  const [edgeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextEdges)
    .innerJoin(contextNodes, eq(contextEdges.fromNodeId, contextNodes.id))
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(eq(discoveries.tenantId, ctx.tenantId));

  // 글로벌 엔티티 수 (distinct globalEntityId)
  const [globalEntityCount] = await db
    .select({ count: sql<number>`COUNT(DISTINCT ${contextNodes.globalEntityId})` })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        sql`${contextNodes.globalEntityId} IS NOT NULL`,
      ),
    );

  // 미검토 노드 수
  const [unreviewedNodeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        eq(contextNodes.autoGenerated, 1),
        eq(contextNodes.reviewed, 0),
      ),
    );

  // 미검토 엣지 수
  const [unreviewedEdgeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextEdges)
    .where(
      and(
        eq(contextEdges.autoGenerated, 1),
        eq(contextEdges.reviewed, 0),
      ),
    );

  // 최근 자동 생성 노드 5개
  const recentNodes = await db
    .select({
      id: contextNodes.id,
      label: contextNodes.label,
      ontologyTypeId: contextNodes.ontologyTypeId,
      confidence: contextNodes.confidence,
      globalEntityId: contextNodes.globalEntityId,
      createdAt: contextNodes.createdAt,
    })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        eq(contextNodes.autoGenerated, 1),
      ),
    )
    .orderBy(sql`${contextNodes.createdAt} DESC`)
    .limit(5);

  // 타입 목록
  const types = await db.select().from(ontologyTypes);

  return json({
    stats: {
      nodes: nodeCount.count,
      edges: edgeCount.count,
      globalEntities: globalEntityCount.count,
      unreviewedNodes: unreviewedNodeCount.count,
      unreviewedEdges: unreviewedEdgeCount.count,
    },
    recentNodes,
    types,
  });
}

interface StatCardProps {
  label: string;
  value: number;
  variant?: "default" | "warning";
}

function StatCard({ label, value, variant = "default" }: StatCardProps) {
  return (
    <Card>
      <CardContent className="p-4">
        <p className="text-xs text-[var(--axis-text-tertiary)]">{label}</p>
        <p
          className={`mt-1 text-2xl font-bold ${
            variant === "warning"
              ? "text-[var(--axis-badge-warning-text)]"
              : "text-[var(--axis-text-primary)]"
          }`}
        >
          {value.toLocaleString()}
        </p>
      </CardContent>
    </Card>
  );
}

export default function OntologySummary() {
  const { stats, recentNodes, types } = useLoaderData<typeof loader>();
  const typeMap = new Map(types.map((t) => [t.id, t]));

  return (
    <div className="space-y-6">
      {/* Stats grid */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
        <StatCard label="전체 노드" value={stats.nodes} />
        <StatCard label="전체 엣지" value={stats.edges} />
        <StatCard label="글로벌 엔티티" value={stats.globalEntities} />
        <StatCard label="미검토 노드" value={stats.unreviewedNodes} variant={stats.unreviewedNodes > 0 ? "warning" : "default"} />
        <StatCard label="미검토 엣지" value={stats.unreviewedEdges} variant={stats.unreviewedEdges > 0 ? "warning" : "default"} />
      </div>

      {/* Recent auto-generated nodes */}
      <div>
        <h2 className="mb-3 text-sm font-semibold text-[var(--axis-text-secondary)]">
          최근 자동 추출 엔티티
        </h2>
        {recentNodes.length === 0 ? (
          <p className="text-sm text-[var(--axis-text-tertiary)]">
            자동 추출된 엔티티가 없습니다. Agent 채팅에서 엔티티 추출을 실행하세요.
          </p>
        ) : (
          <div className="space-y-2">
            {recentNodes.map((node) => {
              const typeInfo = typeMap.get(node.ontologyTypeId ?? "");
              return (
                <Card key={node.id}>
                  <CardContent className="flex items-center gap-3 p-3">
                    {typeInfo && (
                      <span
                        className="flex h-8 w-8 items-center justify-center rounded-full text-sm"
                        style={{ backgroundColor: typeInfo.color + "20", color: typeInfo.color }}
                      >
                        {typeInfo.icon}
                      </span>
                    )}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-[var(--axis-text-primary)]">
                          {node.label}
                        </span>
                        {typeInfo && (
                          <Badge variant="secondary" className="text-[10px]">
                            {typeInfo.nameKo}
                          </Badge>
                        )}
                      </div>
                      <div className="mt-0.5 flex items-center gap-2 text-[10px] text-[var(--axis-text-tertiary)]">
                        <span>신뢰도 {((node.confidence ?? 1) * 100).toFixed(0)}%</span>
                        {node.globalEntityId && <span>글로벌 엔티티</span>}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
