import type { LoaderFunctionArgs } from "@remix-run/cloudflare";
import { json } from "@remix-run/cloudflare";
import { useLoaderData } from "@remix-run/react";
import { eq, and, sql } from "drizzle-orm";
import { getDb } from "~/db";
import { contextNodes, contextEdges, discoveries, ontologyTypes } from "~/db/schema";
import { getSessionContext } from "~/lib/auth/session.server";
import { Card, CardContent } from "~/components/ui/Card";
import { Badge } from "~/components/ui/Badge";
import { GraphViewer } from "~/components/graph/GraphViewer";

export async function loader({ request, context }: LoaderFunctionArgs) {
  const env = context.cloudflare.env as unknown as {
    DB: D1Database;
    SESSION_SECRET: string;
  };
  const db = getDb(env.DB);
  const ctx = await getSessionContext(request, db, env.SESSION_SECRET);
  if (!ctx) throw new Response("Unauthorized", { status: 401 });

  // Stats queries
  const [nodeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(eq(discoveries.tenantId, ctx.tenantId));

  const [edgeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextEdges)
    .innerJoin(contextNodes, eq(contextEdges.fromNodeId, contextNodes.id))
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(eq(discoveries.tenantId, ctx.tenantId));

  const [globalEntityCount] = await db
    .select({ count: sql<number>`COUNT(DISTINCT ${contextNodes.globalEntityId})` })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        sql`${contextNodes.globalEntityId} IS NOT NULL`,
      ),
    );

  const [unreviewedNodeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        eq(contextNodes.autoGenerated, 1),
        eq(contextNodes.reviewed, 0),
      ),
    );

  const [unreviewedEdgeCount] = await db
    .select({ count: sql<number>`COUNT(*)` })
    .from(contextEdges)
    .where(
      and(
        eq(contextEdges.autoGenerated, 1),
        eq(contextEdges.reviewed, 0),
      ),
    );

  // Graph nodes (rejected 제외)
  const graphNodes = await db
    .select({
      id: contextNodes.id,
      label: contextNodes.label,
      ontologyTypeId: contextNodes.ontologyTypeId,
      sourceEvidenceId: contextNodes.sourceEvidenceId,
      metadata: contextNodes.metadata,
    })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        sql`${contextNodes.reviewed} != 2`,
      ),
    );

  const nodeIds = new Set(graphNodes.map((n) => n.id));

  // Graph edges (rejected 제외, 양쪽 노드 존재)
  const allEdges = await db
    .select({
      id: contextEdges.id,
      fromNodeId: contextEdges.fromNodeId,
      toNodeId: contextEdges.toNodeId,
      relationType: contextEdges.relationType,
      strength: contextEdges.strength,
      sourceEvidenceId: contextEdges.sourceEvidenceId,
    })
    .from(contextEdges)
    .where(sql`${contextEdges.reviewed} != 2`);

  const graphEdges = allEdges.filter(
    (e) => nodeIds.has(e.fromNodeId) && nodeIds.has(e.toNodeId),
  );

  // 최근 자동 생성 노드 5개
  const recentNodes = await db
    .select({
      id: contextNodes.id,
      label: contextNodes.label,
      ontologyTypeId: contextNodes.ontologyTypeId,
      confidence: contextNodes.confidence,
      globalEntityId: contextNodes.globalEntityId,
      createdAt: contextNodes.createdAt,
    })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        eq(contextNodes.autoGenerated, 1),
      ),
    )
    .orderBy(sql`${contextNodes.createdAt} DESC`)
    .limit(5);

  const types = await db.select().from(ontologyTypes);

  return json({
    stats: {
      nodes: nodeCount.count,
      edges: edgeCount.count,
      globalEntities: globalEntityCount.count,
      unreviewedNodes: unreviewedNodeCount.count,
      unreviewedEdges: unreviewedEdgeCount.count,
    },
    graphNodes,
    graphEdges,
    recentNodes,
    types,
  });
}

const STAT_ITEMS = [
  { key: "nodes" as const, label: "NODES" },
  { key: "edges" as const, label: "EDGES" },
  { key: "globalEntities" as const, label: "GLOBAL" },
  { key: "unreviewedNodes" as const, label: "UNREV.N", warn: true },
  { key: "unreviewedEdges" as const, label: "UNREV.E", warn: true },
];

export default function LabOverview() {
  const { stats, graphNodes, graphEdges, recentNodes, types } = useLoaderData<typeof loader>();
  const typeMap = new Map(types.map((t) => [t.id, t]));

  const preparedNodes = graphNodes.map((n) => ({
    id: n.id,
    label: n.label,
    ontologyTypeId: n.ontologyTypeId,
    sourceEvidenceId: n.sourceEvidenceId,
    metadata: n.metadata as Record<string, unknown> | null,
  }));

  const preparedEdges = graphEdges.map((e) => ({
    id: e.id,
    fromNodeId: e.fromNodeId,
    toNodeId: e.toNodeId,
    relationType: e.relationType,
    strength: (e.strength ?? 100) / 100,
    sourceEvidenceId: e.sourceEvidenceId,
  }));

  return (
    <div className="space-y-6">
      {/* Instrument Panel — Stats */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
        {STAT_ITEMS.map(({ key, label, warn }) => {
          const value = stats[key];
          const isWarning = warn && value > 0;
          return (
            <Card key={key} className={isWarning ? "lab-instrument-active" : ""}>
              <CardContent className="p-4">
                <p className="lab-stat-terminal">{label}</p>
                <p
                  className={`mt-1 text-[30px] font-bold tabular-nums ${
                    isWarning
                      ? "text-[var(--dx-lab-accent)]"
                      : "text-[var(--axis-text-primary)]"
                  }`}
                  style={{ fontFamily: "var(--dx-font-mono)" }}
                >
                  {value.toLocaleString()}
                </p>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Graph Card */}
      <Card>
        <CardContent className="p-4">
          <div className="mb-3 flex items-center justify-between">
            <p className="lab-stat-terminal">KNOWLEDGE GRAPH</p>
            <span className="text-xs text-[var(--axis-text-tertiary)]" style={{ fontFamily: "var(--dx-font-mono)" }}>
              {graphNodes.length}N / {graphEdges.length}E
            </span>
          </div>
          <GraphViewer
            nodes={preparedNodes}
            edges={preparedEdges}
            ontologyTypes={types}
          />
          {/* Legend */}
          <div className="mt-3 flex flex-wrap gap-4 text-xs text-[var(--axis-text-secondary)]">
            <span className="flex items-center gap-1">
              <span className="inline-block h-0.5 w-6 bg-[var(--axis-badge-success-text)]" /> supports
            </span>
            <span className="flex items-center gap-1">
              <span className="inline-block h-0.5 w-6 border-t-2 border-dashed border-[var(--axis-button-destructive-bg-default)]" /> contradicts
            </span>
            <span className="flex items-center gap-1">
              <span className="inline-block h-0.5 w-6 bg-[var(--axis-badge-purple-text)]" /> causes
            </span>
            <span className="flex items-center gap-1">
              <span className="inline-block h-0.5 w-6 border-t-2 border-dashed border-[var(--axis-text-tertiary)]" /> relates_to
            </span>
            <span className="flex items-center gap-1">
              <span className="inline-block h-0.5 w-6 border-t-2 border-dashed border-[var(--axis-badge-info-text)]" /> depends_on
            </span>
          </div>
        </CardContent>
      </Card>

      {/* Extraction Log — Recent auto-generated nodes */}
      <div>
        <p className="lab-stat-terminal mb-3">EXTRACTION LOG</p>
        {recentNodes.length === 0 ? (
          <p className="text-sm text-[var(--axis-text-tertiary)]" style={{ fontFamily: "var(--dx-font-mono)" }}>
            &gt; No extractions found. Run entity extraction from Agent chat.
          </p>
        ) : (
          <div className="space-y-1.5">
            {recentNodes.map((node) => {
              const typeInfo = typeMap.get(node.ontologyTypeId ?? "");
              return (
                <Card key={node.id}>
                  <CardContent className="flex items-center gap-3 p-3">
                    {typeInfo && (
                      <span
                        className="flex h-8 w-8 items-center justify-center rounded-full text-sm"
                        style={{ backgroundColor: typeInfo.color + "20", color: typeInfo.color }}
                      >
                        {typeInfo.icon}
                      </span>
                    )}
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-[var(--axis-text-primary)]">
                          {node.label}
                        </span>
                        {typeInfo && (
                          <Badge variant="secondary" className="text-[10px]">
                            {typeInfo.nameKo}
                          </Badge>
                        )}
                      </div>
                      <div className="mt-0.5 flex items-center gap-2 text-[10px] text-[var(--axis-text-tertiary)]" style={{ fontFamily: "var(--dx-font-mono)" }}>
                        <span>CONF {((node.confidence ?? 1) * 100).toFixed(0)}%</span>
                        {node.globalEntityId && <span>GLOBAL</span>}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
