import type { LoaderFunctionArgs } from "@remix-run/cloudflare";
import { json } from "@remix-run/cloudflare";
import { useLoaderData, useFetcher } from "@remix-run/react";
import { eq, and, sql } from "drizzle-orm";
import { getDb } from "~/db";
import { contextNodes, contextEdges, ontologyTypes, discoveries } from "~/db/schema";
import { getSessionContext } from "~/lib/auth/session.server";
import { Card, CardContent } from "~/components/ui/Card";
import { Badge } from "~/components/ui/Badge";

export async function loader({ request, context }: LoaderFunctionArgs) {
  const env = context.cloudflare.env as unknown as {
    DB: D1Database;
    SESSION_SECRET: string;
  };
  const db = getDb(env.DB);
  const ctx = await getSessionContext(request, db, env.SESSION_SECRET);
  if (!ctx) throw new Response("Unauthorized", { status: 401 });

  // 미검토 자동생성 노드
  const unreviewedNodes = await db
    .select({
      id: contextNodes.id,
      label: contextNodes.label,
      ontologyTypeId: contextNodes.ontologyTypeId,
      confidence: contextNodes.confidence,
      discoveryId: contextNodes.discoveryId,
      globalEntityId: contextNodes.globalEntityId,
      createdAt: contextNodes.createdAt,
    })
    .from(contextNodes)
    .innerJoin(discoveries, eq(contextNodes.discoveryId, discoveries.id))
    .where(
      and(
        eq(discoveries.tenantId, ctx.tenantId),
        eq(contextNodes.autoGenerated, 1),
        eq(contextNodes.reviewed, 0),
      ),
    )
    .orderBy(sql`${contextNodes.createdAt} DESC`)
    .limit(50);

  // 미검토 자동생성 엣지
  const unreviewedEdges = await db
    .select({
      id: contextEdges.id,
      fromNodeId: contextEdges.fromNodeId,
      toNodeId: contextEdges.toNodeId,
      relationType: contextEdges.relationType,
      strength: contextEdges.strength,
      confidence: contextEdges.confidence,
      createdAt: contextEdges.createdAt,
    })
    .from(contextEdges)
    .where(
      and(
        eq(contextEdges.autoGenerated, 1),
        eq(contextEdges.reviewed, 0),
      ),
    )
    .orderBy(sql`${contextEdges.createdAt} DESC`)
    .limit(50);

  // 타입 목록
  const types = await db.select().from(ontologyTypes);

  return json({ unreviewedNodes, unreviewedEdges, types });
}

const RELATION_LABELS: Record<string, string> = {
  supports: "지지함",
  contradicts: "모순됨",
  causes: "원인됨",
  relates_to: "관련됨",
  depends_on: "의존함",
};

export default function OntologyReview() {
  const { unreviewedNodes, unreviewedEdges, types } = useLoaderData<typeof loader>();
  const fetcher = useFetcher();

  const typeMap = new Map(types.map((t) => [t.id, t]));

  function handleReview(type: "node" | "edge", id: string, action: "approve" | "reject") {
    fetcher.submit(
      JSON.stringify({ type, id, action }),
      { method: "POST", action: "/api/ontology/review", encType: "application/json" },
    );
  }

  const totalCount = unreviewedNodes.length + unreviewedEdges.length;

  return (
    <div className="mx-auto max-w-3xl px-6 py-6">
      <div className="mb-6 flex items-center gap-3">
        <h1 className="text-xl font-bold text-[var(--axis-text-primary)]">온톨로지 검토 큐</h1>
        <Badge variant="secondary">{totalCount}건</Badge>
      </div>

      {totalCount === 0 && (
        <p className="text-sm text-[var(--axis-text-tertiary)]">
          검토할 항목이 없습니다. 자동 추출이 실행되면 여기에 표시됩니다.
        </p>
      )}

      {/* Nodes */}
      {unreviewedNodes.length > 0 && (
        <div className="mb-8">
          <h2 className="mb-3 text-sm font-semibold text-[var(--axis-text-secondary)]">
            엔티티 ({unreviewedNodes.length})
          </h2>
          <div className="space-y-2">
            {unreviewedNodes.map((node) => {
              const typeInfo = typeMap.get(node.ontologyTypeId ?? "");
              return (
                <Card key={node.id}>
                  <CardContent className="flex items-center gap-3 p-3">
                    {typeInfo && (
                      <span
                        className="flex h-8 w-8 items-center justify-center rounded-full text-sm"
                        style={{ backgroundColor: typeInfo.color + "20", color: typeInfo.color }}
                      >
                        {typeInfo.icon}
                      </span>
                    )}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-[var(--axis-text-primary)]">
                          {node.label}
                        </span>
                        {typeInfo && (
                          <Badge variant="secondary" className="text-[10px]">
                            {typeInfo.nameKo}
                          </Badge>
                        )}
                      </div>
                      <div className="mt-0.5 flex items-center gap-2 text-[10px] text-[var(--axis-text-tertiary)]">
                        <span>신뢰도 {((node.confidence ?? 1) * 100).toFixed(0)}%</span>
                        {node.globalEntityId && <span>글로벌 엔티티</span>}
                      </div>
                    </div>
                    <div className="flex gap-1">
                      <button
                        type="button"
                        onClick={() => handleReview("node", node.id, "approve")}
                        disabled={fetcher.state !== "idle"}
                        className="rounded bg-[var(--axis-badge-success-bg,#D1FAE5)] px-2 py-1 text-[10px] font-medium text-[var(--axis-badge-success-text,#065F46)] hover:opacity-80"
                      >
                        승인
                      </button>
                      <button
                        type="button"
                        onClick={() => handleReview("node", node.id, "reject")}
                        disabled={fetcher.state !== "idle"}
                        className="rounded bg-[var(--axis-badge-destructive-bg,#FEE2E2)] px-2 py-1 text-[10px] font-medium text-[var(--axis-badge-destructive-text,#991B1B)] hover:opacity-80"
                      >
                        거절
                      </button>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      )}

      {/* Edges */}
      {unreviewedEdges.length > 0 && (
        <div>
          <h2 className="mb-3 text-sm font-semibold text-[var(--axis-text-secondary)]">
            관계 ({unreviewedEdges.length})
          </h2>
          <div className="space-y-2">
            {unreviewedEdges.map((edge) => (
              <Card key={edge.id}>
                <CardContent className="flex items-center gap-3 p-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1 text-sm">
                      <span className="font-mono text-[var(--axis-text-tertiary)]">{edge.fromNodeId.slice(0, 8)}</span>
                      <span className="text-[var(--axis-text-secondary)]">→</span>
                      <Badge variant="secondary" className="text-[10px]">
                        {RELATION_LABELS[edge.relationType] || edge.relationType}
                      </Badge>
                      <span className="text-[var(--axis-text-secondary)]">→</span>
                      <span className="font-mono text-[var(--axis-text-tertiary)]">{edge.toNodeId.slice(0, 8)}</span>
                    </div>
                    <div className="mt-0.5 flex items-center gap-2 text-[10px] text-[var(--axis-text-tertiary)]">
                      <span>강도 {((edge.strength ?? 100) / 100).toFixed(2)}</span>
                      <span>신뢰도 {((edge.confidence ?? 1) * 100).toFixed(0)}%</span>
                    </div>
                  </div>
                  <div className="flex gap-1">
                    <button
                      type="button"
                      onClick={() => handleReview("edge", edge.id, "approve")}
                      disabled={fetcher.state !== "idle"}
                      className="rounded bg-[var(--axis-badge-success-bg,#D1FAE5)] px-2 py-1 text-[10px] font-medium text-[var(--axis-badge-success-text,#065F46)] hover:opacity-80"
                    >
                      승인
                    </button>
                    <button
                      type="button"
                      onClick={() => handleReview("edge", edge.id, "reject")}
                      disabled={fetcher.state !== "idle"}
                      className="rounded bg-[var(--axis-badge-destructive-bg,#FEE2E2)] px-2 py-1 text-[10px] font-medium text-[var(--axis-badge-destructive-text,#991B1B)] hover:opacity-80"
                    >
                      거절
                    </button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
