import { describe, it, expect, beforeEach } from "vitest";
import { eq } from "drizzle-orm";
import { createTestDb, type TestDB } from "../../helpers/db";
import {
  makeUser,
  makeDiscovery,
  makeContextNode,
  makeContextEdge,
  resetFixtureCounter,
} from "../../helpers/fixtures";
import {
  discoveries,
  users,
  contextNodes,
  contextEdges,
  ontologyTypes,
  tenants,
  tenantMembers,
} from "~/db";
import { matchGlobalEntity } from "~/lib/ontology/matcher";
import {
  detectClusters,
  detectContradictions,
} from "~/lib/ontology/analyzer";

type AnalyzerDB = Parameters<typeof detectClusters>[0];
function asAnalyzerDB(db: TestDB): AnalyzerDB {
  return db as unknown as AnalyzerDB;
}

type MatcherDB = Parameters<typeof matchGlobalEntity>[0];
function asMatcherDB(db: TestDB): MatcherDB {
  return db as unknown as MatcherDB;
}

function seedTenant(db: TestDB) {
  const user = makeUser({ id: "user-1" });
  db.insert(users).values(user).run();

  db.insert(tenants)
    .values({
      id: "tenant-1",
      name: "Test Tenant",
      slug: "test-tenant",
      ownerUserId: "user-1",
    })
    .run();

  db.insert(tenantMembers)
    .values({ id: "tm-1", tenantId: "tenant-1", userId: "user-1" })
    .run();

  db.insert(ontologyTypes)
    .values([
      { id: "ONT-03", nameKo: "규제", domain: "regulation", color: "#333" },
      { id: "ONT-07", nameKo: "금융", domain: "finance", color: "#777" },
      { id: "ONT-10", nameKo: "기술", domain: "tech", color: "#AAA" },
    ])
    .onConflictDoNothing()
    .run();
}

describe("Ontology review + cross-Discovery pipeline", () => {
  let db: TestDB;

  beforeEach(() => {
    resetFixtureCounter();
    db = createTestDb();
    seedTenant(db);
  });

  // ─── Node review ─────────────────────────────────────────────────

  describe("node review", () => {
    it("자동생성 노드 → approve → reviewed=1", () => {
      const disc = makeDiscovery({ id: "disc-1", tenantId: "tenant-1" });
      db.insert(discoveries).values(disc).run();

      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "node-auto",
            discoveryId: "disc-1",
            label: "자동 엔티티",
            autoGenerated: 1,
            reviewed: 0,
          }),
        )
        .run();

      // Simulate approve via direct DB update
      db.update(contextNodes)
        .set({ reviewed: 1 })
        .where(eq(contextNodes.id, "node-auto"))
        .run();

      const row = db
        .select()
        .from(contextNodes)
        .where(eq(contextNodes.id, "node-auto"))
        .all()[0];
      expect(row.reviewed).toBe(1);
      expect(row.autoGenerated).toBe(1);
    });

    it("자동생성 노드 → reject → reviewed=2", () => {
      const disc = makeDiscovery({ id: "disc-1", tenantId: "tenant-1" });
      db.insert(discoveries).values(disc).run();

      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "node-auto",
            discoveryId: "disc-1",
            label: "거절 대상",
            autoGenerated: 1,
            reviewed: 0,
          }),
        )
        .run();

      db.update(contextNodes)
        .set({ reviewed: 2 })
        .where(eq(contextNodes.id, "node-auto"))
        .run();

      const row = db
        .select()
        .from(contextNodes)
        .where(eq(contextNodes.id, "node-auto"))
        .all()[0];
      expect(row.reviewed).toBe(2);
    });

    it("자동생성 노드 → edit(label 변경) → reviewed=1, 새 label", () => {
      const disc = makeDiscovery({ id: "disc-1", tenantId: "tenant-1" });
      db.insert(discoveries).values(disc).run();

      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "node-auto",
            discoveryId: "disc-1",
            label: "원래 라벨",
            autoGenerated: 1,
            reviewed: 0,
          }),
        )
        .run();

      // Simulate edit-and-approve
      db.update(contextNodes)
        .set({ label: "수정된 라벨", reviewed: 1 })
        .where(eq(contextNodes.id, "node-auto"))
        .run();

      const row = db
        .select()
        .from(contextNodes)
        .where(eq(contextNodes.id, "node-auto"))
        .all()[0];
      expect(row.reviewed).toBe(1);
      expect(row.label).toBe("수정된 라벨");
    });
  });

  // ─── Edge review ─────────────────────────────────────────────────

  describe("edge review", () => {
    it("자동생성 엣지 → approve → reviewed=1", () => {
      const disc = makeDiscovery({ id: "disc-1", tenantId: "tenant-1" });
      db.insert(discoveries).values(disc).run();

      const n1 = makeContextNode({ id: "n1", discoveryId: "disc-1", label: "A" });
      const n2 = makeContextNode({ id: "n2", discoveryId: "disc-1", label: "B" });
      db.insert(contextNodes).values(n1).run();
      db.insert(contextNodes).values(n2).run();

      db.insert(contextEdges)
        .values({
          ...makeContextEdge({ id: "edge-auto", fromNodeId: "n1", toNodeId: "n2" }),
          autoGenerated: 1,
          reviewed: 0,
        })
        .run();

      db.update(contextEdges)
        .set({ reviewed: 1 })
        .where(eq(contextEdges.id, "edge-auto"))
        .run();

      const row = db
        .select()
        .from(contextEdges)
        .where(eq(contextEdges.id, "edge-auto"))
        .all()[0];
      expect(row.reviewed).toBe(1);
      expect(row.autoGenerated).toBe(1);
    });
  });

  // ─── Cross-Discovery globalEntityId ──────────────────────────────

  describe("cross-Discovery global entity", () => {
    it("같은 label + ontologyTypeId → 동일 globalEntityId 매칭", async () => {
      const disc1 = makeDiscovery({ id: "disc-1", tenantId: "tenant-1" });
      const disc2 = makeDiscovery({ id: "disc-2", tenantId: "tenant-1" });
      db.insert(discoveries).values(disc1).run();
      db.insert(discoveries).values(disc2).run();

      // First entity — creates a new globalEntityId
      const match1 = await matchGlobalEntity(asMatcherDB(db), "AI 기술", "ONT-10");
      expect(match1.isNew).toBe(true);

      // Insert node with globalEntityId
      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "nodeA",
            discoveryId: "disc-1",
            label: "AI 기술",
            ontologyTypeId: "ONT-10",
            globalEntityId: match1.globalEntityId,
          }),
        )
        .run();

      // Second entity with same label — should match existing
      const match2 = await matchGlobalEntity(asMatcherDB(db), "AI 기술", "ONT-10");
      expect(match2.isNew).toBe(false);
      expect(match2.globalEntityId).toBe(match1.globalEntityId);

      // Insert second node
      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "nodeB",
            discoveryId: "disc-2",
            label: "AI 기술",
            ontologyTypeId: "ONT-10",
            globalEntityId: match2.globalEntityId,
          }),
        )
        .run();

      // Both nodes share the same globalEntityId
      const allNodes = db.select().from(contextNodes).all();
      expect(allNodes[0].globalEntityId).toBe(allNodes[1].globalEntityId);
    });
  });

  // ─── Rejected nodes excluded from analysis ───────────────────────

  describe("rejected node exclusion", () => {
    it("reviewed=2 노드가 분석에서 제외됨", async () => {
      const disc = makeDiscovery({ id: "disc-1", tenantId: "tenant-1" });
      db.insert(discoveries).values(disc).run();

      // Active node pair
      const n1 = makeContextNode({
        id: "n1",
        discoveryId: "disc-1",
        label: "활성A",
        reviewed: 1,
      });
      const n2 = makeContextNode({
        id: "n2",
        discoveryId: "disc-1",
        label: "활성B",
        reviewed: 1,
      });
      // Rejected node
      const n3 = makeContextNode({
        id: "n3",
        discoveryId: "disc-1",
        label: "거절됨",
        reviewed: 2,
      });
      db.insert(contextNodes).values(n1).run();
      db.insert(contextNodes).values(n2).run();
      db.insert(contextNodes).values(n3).run();

      // Edges: n1-n2 (active), n1-n3 (involves rejected node)
      db.insert(contextEdges)
        .values(
          makeContextEdge({
            id: "e1",
            fromNodeId: "n1",
            toNodeId: "n2",
            relationType: "supports",
          }),
        )
        .run();
      db.insert(contextEdges)
        .values(
          makeContextEdge({
            id: "e2",
            fromNodeId: "n1",
            toNodeId: "n3",
            relationType: "contradicts",
          }),
        )
        .run();

      // Contradiction analysis should NOT find contradiction because n3 is rejected
      const contradictions = await detectContradictions(
        asAnalyzerDB(db),
        "tenant-1",
      );
      expect(contradictions).toEqual([]);

      // Cluster analysis should only see n1-n2 cluster (not n3)
      const clusters = await detectClusters(asAnalyzerDB(db), "tenant-1");
      expect(clusters.length).toBe(1);
      expect(clusters[0].nodes.length).toBe(2);
      const labels = clusters[0].nodes.map((n: { label: string }) => n.label).sort();
      expect(labels).toEqual(["활성A", "활성B"]);
    });
  });

  // ─── Full pipeline ───────────────────────────────────────────────

  describe("full pipeline: cross-Discovery + cluster analysis", () => {
    it("교차 엔티티 → 글로벌 매칭 → 하나의 클러스터로 감지", async () => {
      const disc1 = makeDiscovery({ id: "disc-1", tenantId: "tenant-1" });
      const disc2 = makeDiscovery({ id: "disc-2", tenantId: "tenant-1" });
      db.insert(discoveries).values(disc1).run();
      db.insert(discoveries).values(disc2).run();

      // Step 1: Create shared entity via matchGlobalEntity
      const match = await matchGlobalEntity(asMatcherDB(db), "블록체인", "ONT-10");
      const sharedGlobalId = match.globalEntityId;

      // Step 2: Insert nodes in disc-1
      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "d1-n1",
            discoveryId: "disc-1",
            label: "블록체인",
            ontologyTypeId: "ONT-10",
            globalEntityId: sharedGlobalId,
            reviewed: 1,
          }),
        )
        .run();
      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "d1-n2",
            discoveryId: "disc-1",
            label: "스마트계약",
            ontologyTypeId: "ONT-03",
            reviewed: 1,
          }),
        )
        .run();

      // Step 3: Insert nodes in disc-2 — "블록체인" gets same globalEntityId
      const match2 = await matchGlobalEntity(
        asMatcherDB(db),
        "블록체인",
        "ONT-10",
      );
      expect(match2.globalEntityId).toBe(sharedGlobalId);

      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "d2-n1",
            discoveryId: "disc-2",
            label: "블록체인",
            ontologyTypeId: "ONT-10",
            globalEntityId: sharedGlobalId,
            reviewed: 1,
          }),
        )
        .run();
      db.insert(contextNodes)
        .values(
          makeContextNode({
            id: "d2-n2",
            discoveryId: "disc-2",
            label: "DeFi",
            ontologyTypeId: "ONT-07",
            reviewed: 1,
          }),
        )
        .run();

      // Step 4: Connect within each discovery
      db.insert(contextEdges)
        .values(
          makeContextEdge({
            id: "e1",
            fromNodeId: "d1-n1",
            toNodeId: "d1-n2",
            relationType: "relates_to",
          }),
        )
        .run();
      db.insert(contextEdges)
        .values(
          makeContextEdge({
            id: "e2",
            fromNodeId: "d2-n1",
            toNodeId: "d2-n2",
            relationType: "relates_to",
          }),
        )
        .run();

      // Step 5: Cluster analysis — d1-n1 and d2-n1 share globalEntityId,
      // so all 4 nodes should form a single cluster
      const clusters = await detectClusters(asAnalyzerDB(db), "tenant-1");

      expect(clusters.length).toBe(1);
      expect(clusters[0].nodes.length).toBe(4);
      expect(clusters[0].edgeCount).toBe(2);

      // Verify nodes from both discoveries are present
      const discoveryIds = new Set(
        clusters[0].nodes.map((n: { discoveryId: string }) => n.discoveryId),
      );
      expect(discoveryIds.has("disc-1")).toBe(true);
      expect(discoveryIds.has("disc-2")).toBe(true);
    });
  });
});
